<?php

namespace Classes\Utils\Section\Steel\Russian;

/**
 * Class make string naem of section type
 *
 * @author Noskov Alexey
 */
 class GOST_26020 extends \Classes\Utils\Section\Steel\Assortment {
     
    protected $collection = array(
             "10B1" => "STZ RUSSIAN p_norm_b 1",
             "12B1" => "STZ RUSSIAN p_norm_b 2",
             "12B2" => "STZ RUSSIAN p_norm_b 3",
             "14B1" => "STZ RUSSIAN p_norm_b 4",
             "14B2" => "STZ RUSSIAN p_norm_b 5",
             "16B1" => "STZ RUSSIAN p_norm_b 6",
             "16B2" => "STZ RUSSIAN p_norm_b 7",
             "18B1" => "STZ RUSSIAN p_norm_b 8",
             "18B2" => "STZ RUSSIAN p_norm_b 9",
             "20B1" => "STZ RUSSIAN p_norm_b 10",
             "23B1" => "STZ RUSSIAN p_norm_b 11",
             "26B1" => "STZ RUSSIAN p_norm_b 12",
             "26B2" => "STZ RUSSIAN p_norm_b 13",
             "30B1" => "STZ RUSSIAN p_norm_b 14",
             "30B2" => "STZ RUSSIAN p_norm_b 15",
             "35B1" => "STZ RUSSIAN p_norm_b 16",
             "35B2" => "STZ RUSSIAN p_norm_b 17",
             "40B1" => "STZ RUSSIAN p_norm_b 18",
             "40B2" => "STZ RUSSIAN p_norm_b 19",
             "45B1" => "STZ RUSSIAN p_norm_b 20",
             "45B2" => "STZ RUSSIAN p_norm_b 21",
             "50B1" => "STZ RUSSIAN p_norm_b 22",
             "50B2" => "STZ RUSSIAN p_norm_b 23",
             "55B1" => "STZ RUSSIAN p_norm_b 24",
             "55B2" => "STZ RUSSIAN p_norm_b 25",
             "60B1" => "STZ RUSSIAN p_norm_b 26",
             "60B2" => "STZ RUSSIAN p_norm_b 27",
             "70B1" => "STZ RUSSIAN p_norm_b 28",
             "70B2" => "STZ RUSSIAN p_norm_b 29",
             "80B1" => "STZ RUSSIAN p_norm_b 30",
             "80B2" => "STZ RUSSIAN p_norm_b 31",
             "90B1" => "STZ RUSSIAN p_norm_b 32",
             "90B2" => "STZ RUSSIAN p_norm_b 33",
             "100B1" => "STZ RUSSIAN p_norm_b 34",
             "100B2" => "STZ RUSSIAN p_norm_b 35",
             "100B3" => "STZ RUSSIAN p_norm_b 36",
             "100B4" => "STZ RUSSIAN p_norm_b 37",
             
             "20SH1" => "STZ RUSSIAN p_wide_h 1",
             "23SH1" => "STZ RUSSIAN p_wide_h 2",
             "26SH1" => "STZ RUSSIAN p_wide_h 3",
             "26SH2" => "STZ RUSSIAN p_wide_h 4",
             "30SH1" => "STZ RUSSIAN p_wide_h 5",
             "30SH2" => "STZ RUSSIAN p_wide_h 6",
             "30SH3" => "STZ RUSSIAN p_wide_h 7",
             "35SH1" => "STZ RUSSIAN p_wide_h 8",
             "35SH2" => "STZ RUSSIAN p_wide_h 9",
             "35SH3" => "STZ RUSSIAN p_wide_h 10",
             "40SH1" => "STZ RUSSIAN p_wide_h 11",
             "40SH2" => "STZ RUSSIAN p_wide_h 12",
             "40SH3" => "STZ RUSSIAN p_wide_h 13",
             "50SH1" => "STZ RUSSIAN p_wide_h 14",
             "50SH2" => "STZ RUSSIAN p_wide_h 15",
             "50SH3" => "STZ RUSSIAN p_wide_h 16",
             "50SH4" => "STZ RUSSIAN p_wide_h 17",
             "60SH1" => "STZ RUSSIAN p_wide_h 18",
             "60SH2" => "STZ RUSSIAN p_wide_h 19",
             "60SH3" => "STZ RUSSIAN p_wide_h 20",
             "60SH4" => "STZ RUSSIAN p_wide_h 21",
             "70SH1" => "STZ RUSSIAN p_wide_h 22",
             "70SH2" => "STZ RUSSIAN p_wide_h 23",
             "70SH3" => "STZ RUSSIAN p_wide_h 24",
             "70SH4" => "STZ RUSSIAN p_wide_h 25",
             "70SH5" => "STZ RUSSIAN p_wide_h 26",
             
             "20K1" => "STZ RUSSIAN p_col_k 1",
             "20K2" => "STZ RUSSIAN p_col_k 2",
             "23K1" => "STZ RUSSIAN p_col_k 3",
             "23K2" => "STZ RUSSIAN p_col_k 4",
             "26K1" => "STZ RUSSIAN p_col_k 5",
             "26K2" => "STZ RUSSIAN p_col_k 6",
             "26K3" => "STZ RUSSIAN p_col_k 7",
             "30K1" => "STZ RUSSIAN p_col_k 8",
             "30K2" => "STZ RUSSIAN p_col_k 9",
             "30K3" => "STZ RUSSIAN p_col_k 10",
             "35K1" => "STZ RUSSIAN p_col_k 11",
             "35K2" => "STZ RUSSIAN p_col_k 12",
             "35K3" => "STZ RUSSIAN p_col_k 13",
             "40K1" => "STZ RUSSIAN p_col_k 14",
             "40K2" => "STZ RUSSIAN p_col_k 15",
             "40K3" => "STZ RUSSIAN p_col_k 16",
             "40K4" => "STZ RUSSIAN p_col_k 17",
             "40K5" => "STZ RUSSIAN p_col_k 18"
         );
}
