<script type="text/javascript" src="web/js/cds_functions.js"></script>

<script type='text/javascript'>
    $(document).ready(function () {
        $("#button_execute").click(function (s) {
            s.preventDefault();
            execute();
        });

//        function handleDrop(e) {
//            e.stopPropagation();
//            e.preventDefault();
//
//            var file = e.dataTransfer.files[0];
//            $("#text_area").text(file.name);
//            console.log(file.name);
//            console.log(file.type);
//            console.log(file.size);
//            console.log(file);
//
//            var reader = new FileReader();
//            reader.onload = function (event) {
//                data = event.target.result;
//                var commandArray = data.split('\n');
//                console.log(commandArray);
//                execute(commandArray);
//            };
//            reader.readAsText(file, "UTF-8");
//
//
//        }
//
//        function handleDragOver(e) {
//            e.stopPropagation();
//            e.preventDefault();
//
//            dropZone.addClass('hover');
//        }
//
//        function handleDragEnter(e) {
//            e.stopPropagation();
//            e.preventDefault();
//        }
//
//        function handleDragLeave(e) {
//            e.stopPropagation();
//            e.preventDefault();
//
//            dropZone.removeClass('hover');
//        }
//
//        var dropZone = document.getElementById('drop_zone');
//
//        dropZone.addEventListener('dragenter', handleDragEnter, false);
//        dropZone.addEventListener('dragover', handleDragOver, false);
//        dropZone.addEventListener('dragleave', handleDragLeave, false);
//        dropZone.addEventListener('drop', handleDrop, false);

//        $("div#dropbox").dropzone({url: "index.php"});
        var myDropzone = new Dropzone("div#dropbox", {url: "index.php",
            parallelUploads: 100, uploadMultiple: true});

//        Dropzone.options.dropbox = {
//            init: function () {
//                this.on('sending', function (file, xhr, formData) {
//                    formData.append('cmd', 'Execute');
//                });
//            }
//        };


        myDropzone.on('sending', function (file, xhr, formData) {
            formData.append('cmd', 'Execute');
        });

    });
</script>

<body>

    <style type="text/css">
        #drop_zone, #dropbox {
            border: 2px dashed #bbb;
            -moz-border-radius: 5px;
            -webkit-border-radius: 5px;
            border-radius: 5px;
            padding: 25px;
            text-align: center;
            font-family: sans-serif;
            font-size: 1.5em;
            color: #bbb;
        }
        #info {
            font-family: monospace;
            font-size: 18px;
        }
        #list {
            font-size: 15px;
        }
    </style>

    <div id="drop_zone">Drop script file here</div>
    <div id="dropbox">Dropzone Script</div>

    <div id="info">
        <p></p>
        <ul id="list"></ul>
    </div>
    <div id="text_area"></div>  

</body>