<?php
$data = $request->getFeedback();
$transmit = array_pop($data);
?>
<b><?php echo $transmit;?>.XLS CHECK:</b>
<br/>

<?php
$feedback = array_pop($data);

if (isset($feedback['count'])) {
    ?>There are <?php echo $feedback['count']; ?> new documents in repository<br/><?php
}

if (isset($feedback['error'])) {
    foreach ($feedback['error'] as $status_item) {
        ?><font color="red"><?php echo $status_item->getStatusName(); ?></font><br/><?php
    }
}

if (isset($feedback['uploaders'])) {
    foreach ($feedback['uploaders'] as $file_uploader) {
        $name = \util\Utils::createDocumentName($file_uploader->getDocument()->getProject(), $file_uploader->getDocument()->getDrawing(), $file_uploader->getDocument()->getRevision());
        ?>
        <font color="<?php
        if ($file_uploader->getStatus()->is_OK() === TRUE) {
            echo 'green';
        } else {
            echo 'red';
        }
        ?>">
        <?php echo $name; ?> : <?php echo $file_uploader->getStatus()->getStatusName(); ?>
        </font>
        <br/>
        <?php
    }
}



//Считаем время выполнения скрипта
//\util\Timer::stop('feedback');
//\util\Timer::show('feedback', 'Feedback = ');

//Считаем время выполнения скрипта
//\util\Timer::stop('get_transmittal');
echo 'TIME = ' . \util\Timer::show('GLOBAL') . ' sec.';
?>