<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>MODEL CONSTRUCTOR</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta content="ru" name="content-language"/>

    <script type="text/javascript" src="web/js/jquery-2.1.4.min.js"></script>
    <script type="text/javascript" src="web/js/dropzone.js"></script>
    <script type="text/javascript" src="web/js/jquery.fileDownload.js"></script>
    
</head>

    <?php require array_pop($request->getFeedback());?>

</html> 