<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>TAF PROJECT</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta content="ru" name="content-language"/>

    <link type="text/css" href="web/css/jquery-ui-1.8.17.custom.css" rel="stylesheet"/>
    <link type="text/css" href="web/css/search_results.css" rel="stylesheet"/>
    <link type="text/css" href="web/css/tablesorter/theme.blue.css" rel="stylesheet">
    
    <script type="text/javascript" src="web/js/jquery-1.8.2.min.js"></script>
    <script type="text/javascript" src="web/js/jquery-ui-1.8.17.custom.min.js"></script>
    <script type="text/javascript" src="web/js/jquery.tablesorter.js"></script>
    
</head>

    <?php require array_pop($request->getFeedback());?>

</html> 