<b>NEW TRANSMITTALS:</b>
<br/>
<?php
$transmit_list = array_pop($request->getFeedback());
if (count($transmit_list) == 0) {
    ?>
    Nothing for checking...
    <?php
} else {
    $i=0;
    foreach ($transmit_list as $transmit) {
        $i++;
        ?>
        <a id="transmittal" href="<?php echo $transmit; ?>">: "<?php echo $transmit; ?>" :</a>
        <?php
        if ($i > 6) {
            ?><br/><?php
            $i = 0;
        }
    }
}?>