<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>TAF PROJECT</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta content="ru" name="content-language"/>

        <link rel="stylesheet" href="web/css/statistic.css"/>
        <link rel="stylesheet" href="web/css/morris.css"/>

        <script type="text/javascript" src="web/js/jquery-1.8.2.min.js"></script>
        <script type="text/javascript" src="web/js/raphael-2.1.0.min.js"></script>
        <script type="text/javascript" src="web/js/morris.min.js"></script>
        <script type="text/javascript" src="web/js/stat_functions.js"></script>
        <script>
            $(document).ready(function() {

                //Сдвигаем день
                $("input[id^=button_day]").click(function() {
                    window.day_offset = window.day_offset + parseInt($(this).attr('offset'));
                    if (window.day_offset > 0) {
                        window.day_offset = 0;
                    } else {
                        //Меняем метку
                        var d = new Date();
                        d.setDate(d.getDate() + window.day_offset);
                        //Получаем данные
                        getData('day', window.day_offset, function(result) {
                            $('#day_label').text(makeDayLabel(d, result[2]));
                            window.day_chart.setData(result[0]);
                            createDonut('day_donut', result[1]);
                        });
                    }
                });

                //Сдвигаем месяц
                $("input[id^=button_month]").click(function() {
                    window.month_offset = window.month_offset + parseInt($(this).attr('offset'));
                    if (window.month_offset > 0) {
                        window.month_offset = 0;
                    } else {
                        //Меняем метку
                        var d = new Date();
                        d.setMonth(d.getMonth() + window.month_offset);
                        //Получаем данные
                        getData('month', window.month_offset, function(result) {
                            $('#month_label').text(makeMonthLabel(d, result[2]));
                            window.month_chart.setData(result[0]);
                            createDonut('month_donut', result[1]);
                        });
                    }
                });

                //Рисуем графики
                window.day_chart = createChart('day_chart');
                window.month_chart = createChart('month_chart');


                //Устанавливаем дату на сегодня
                window.day_offset = 0;
                window.month_offset = 0;
                var d = new Date();

                //Получаем данные для месячного графика
                getData('month', window.month_offset, function(result) {
                    //Меняем метку
                    $('#month_label').text(makeMonthLabel(d, result[2]));
                    //Получаем данные
                    window.month_chart.setData(result[0]);
                    createDonut('month_donut', result[1]);
                });


                //Получаем данные для дневного графика
                getData('day', window.day_offset, function(result) {
//                    console.log(result);
                    //Меняем метку
                    $('#day_label').text(makeDayLabel(d, result[2]));
                    //Получаем данные
                    window.day_chart.setData(result[0]);
                    createDonut('day_donut', result[1]);
                });

            });

        </script>


    </head>
    <body>      
        <div id="day_label" class="label" ></div>
        <div class="chart_space">
            <div class="chart_button_size">
                <input type="button" class="chart_button_style" id="button_day_back" value="<" offset="-1"/>
            </div>
            <div id="day_chart" class = "chart_size"></div>
            <div class="chart_button_size">
                <input type="button" class="chart_button_style" id="button_day_forward" value=">" offset="1"/>
            </div>
            <div id="day_donut" class="donut_size"></div>
        </div>

        <div id="month_label" class="label" ></div>
        <div class="chart_space">
            <div class="chart_button_size">
                <input type="button" class="chart_button_style" id="button_month_back" value="<" offset="-1"/>
            </div>
            <div id="month_chart" class = "chart_size"></div>
            <div class="chart_button_size">
                <input type="button" class="chart_button_style" id="button_month_forward" value=">" offset="1"/>
            </div>
            <div id="month_donut" class="donut_size"></div>
        </div>

    </body>
    <script>

    </script>
</html> 