<?php
namespace Classes\Instance;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-21 at 11:57:15.
 */
class InstanceTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Value
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Instance();
    }

    /**
     * @covers Classes\Instance\Instance::getUin
     */
    public function testGetUin()
    {
        $this->assertInternalType('string', $this->object->getUin());
    }

    
}
