<?php
namespace Classes\Value;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-21 at 11:57:15.
 */
class IntValueTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Value
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new IntValue(3);
    }

    /**
     * @covers Classes\Value\Value::get
     * @todo   Implement testGet().
     */
    public function testGet()
    {
        $this->assertEquals(
          3,
          $this->object->get()
        );
    }

    /**
     * @covers Classes\Value\Value::set
     * @todo   Implement testSet().
     */
    public function testSet_1()
    {
        $this->object->set((int)5);
        
        $this->assertEquals(
          (int)5,
          $this->object->get()
        );
    }
    
    /**
     * @covers Classes\Value\Value::set
     * @todo   Implement testSet().
     * 
     * @expectedException \Classes\Exception\Value\EmptyArgumentException
     */
    public function testSet_2()
    {
        $this->object->set();
    }
    
    /**
     * @covers Classes\Value\Value::set
     * @todo   Implement testSet().
     * 
     * @expectedException \Classes\Exception\Value\InvalidArgumentException
     */
    public function testSet_3()
    {
        $this->object->set(3.5);
        
    }
}
