<?php
namespace Classes\Value;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-21 at 11:57:15.
 */
class StringValueTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Value
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new StringValue('Hello');
    }

    /**
     * @covers Classes\Value\Value::get
     * @todo   Implement testGet().
     */
    public function testGet()
    {
        $this->assertEquals(
          'Hello',
          $this->object->get()
        );
    }

    /**
     * @covers Classes\Value\Value::set
     * @todo   Implement testSet().
     */
    public function testSet_1()
    {
        $this->object->set('One');
        
        $this->assertEquals(
          'One',
          $this->object->get()
        );
    }
    
    /**
     * @covers Classes\Value\Value::set
     * @todo   Implement testSet().
     * 
     * @expectedException \Classes\Exception\Value\EmptyArgumentException
     */
    public function testSet_2()
    {
        $this->object->set();
    }
    
    /**
     * @covers Classes\Value\Value::set
     * @todo   Implement testSet().
     * 
     * @expectedException \Classes\Exception\Value\InvalidArgumentException
     */
    public function testSet_3()
    {
        $this->object->set(1);
        
    }
}
